name: Update AWS S3 docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deploy to staging
    runs-on: ubuntu-latest

    # [steps] A sequence of tasks
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Rebuild docs
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run docs
    - run: node ./dist/bin/index.js tag-manager ./docs ${{ secrets.GTM_CONTAINER_ID }}

    - name: Update docs
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'docs'
        DEST_DIR: 'node-wsh-packager'
